version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-app
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: ubuntu-scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: ubuntu-scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: ubuntu-scripts/application_start.sh
      timeout: 300
      runas: ubuntu