version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node-app
hooks:
  ApplicationStop:
    - location: ubuntu-scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: ubuntu-scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ubuntu-scripts/application_start.sh
      timeout: 300
      runas: ec2-user